# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zassmin
description: > # this means to ignore newlines until "baseurl:"
  © 2016 All Rights Reserved. About Zassmin, by Zassmin. 
  I have a no bullshit policy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zassmin.com" # the base hostname & protocol for your site
twitter_username: _zassmin
github_username:  zassmin
linkedin_username:  zassmin

# Build settings
markdown: kramdown

permalink: pretty
